"""init

Revision ID: f6a506c4d9c5
Revises: 
Create Date: 2026-05-14 18:14:22.369987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6a506c4d9c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('experience_min', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('preferred_roles', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('remote_ok', sa.Boolean(), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('jobs')
    # ### end Alembic commands ###
